language: csharp
mono: none
dotnet: 3.1
stages:
- test
- build
jobs:
  include:
  - stage: test
    script:
    - dotnet restore
    - dotnet test
  - stage: build
    script:
    - dotnet restore
    - dotnet build -c Release
    - dotnet pack -c Release
    deploy:
      skip_cleanup: true
      provider: script
      script: dotnet nuget push ./src/Docmosis.Templates/bin/Release/Docmosis.Templates.*.nupkg
        -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
      on:
        branch: master
env:
  global:
    secure: sUKhsti7yauKb/fi41CUtwtX/sGYernLb0pvvxB1+Ke4mKcq+dTuNA2QiTp9mPVXZUiMAgupy/x+juMc9B+RfoYONiCyODkAlin+//tvdAO0sUR6qLkwlEhzR7gGPd4oQ4L3ahiNQpbVtW1yFB2gxNhdvsPx8ZadvUg8Gk6H6mIBRZQ6VhkayzfWukMmZnUF9xnwEMYzbYrxKIEp1m5RjDZ1/ecfhv6X3R87f98NYRL1Mw+O61AA6TOt/Rx57HGA5aMSbNb8r6hi7TRWVPtb6GAOF+PJOISWeOLY6CAv2AkciQGlek7XOJoVSSrF64pJT8Ucvkw7fhkj+ujMOIML1piTO5bZVLrw86+FohhYtl1jwnmxSkSI4xxPGD8y9TS0qCQpksR6p/fB3n8aBeF4dJAWasmo4d6316ekveiAmH5u04BbN5s64iFPjFLgnKD3wi5VsyQoeSkgZ/b75wdM6BQb2NT1Dapd9GXTvdDKOYKhp2O8v3vX+NF4nkw+y6ry3cyQs5kS2ta5F35DvzotaQCWHLdKiVKezwSoQwAfOl9mUELNY2e5EwQ/VGlhB2dru2NbFB/eeaajzdX+knluAd5QDiBLWlcxkQWt0BbAer9/zqE0PUTdOXOCMyxW3glu8driEQ6sfu+aWgnTsd/eX05JELgVgMYgnPMTwSpRLy4=
